from .tensor import Tensor
import numpy as np

class SGD:
    def __init__(self, params: list[Tensor], lr: float, momentum: float = 0.0): ...
    
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class Momentum:
    def __init__(self, params: list[Tensor], lr: float, momentum: float = 0.9): ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class AdaGrad:
    def __init__(self, params: list[Tensor], lr: float, eps: float = 1e-8): ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class Adam:
    def __init__(self, params: list[Tensor], lr: float = 1e-3, beta1: float = 0.9, beta2: float = 0.999, eps: float = 1e-8): ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...